### ISSUE TITLE
Adds support for --no-ssl-bump-domains connection flag

### ISSUE THREAD

**Issue by fernandosouza** [bermi/sauce-connect-launcher#112]

**Comment by jahtalab** [comment]
@fernandosouza , 

You can just add `noSslBumpDomains: 'all'` to your config.

**Comment by julmot** [comment]
@jahtalab Thanks for this information. Where did you take the value `all` from? The documentation doesn't define that:

![2017-01-17_215722](https://cloud.githubusercontent.com/assets/8310677/22039510/efc0594a-dcff-11e6-952e-7e39066a6861.png)

Also, do you know why passing `-B` doesn't work as a replacement for `noSsslBumpDomains` (see https://github.com/karma-runner/karma-sauce-launcher/issues/110)?

**Comment by jahtalab** [comment]
@julmot , The issue for me was some security warning on android and I found the answer in this [thread](https://support.saucelabs.com/customer/portal/questions/13056252-security-certificate-problem-on-android-simulators-appium-back-end-with-sauce-connect)

Looking at the code, I think `-B` doesn't work because it tries to convert camelCase to kebab-case.
