### ISSUE TITLE
Help needed? 

### ISSUE THREAD

**Issue by johanneswuerbach** [bermi/sauce-connect-launcher#87]
It looks like the current project maintainers no longer have time / interest to maintain this module  (unanswered issues / PRs, no CI).

If this is the case, would you be open to add further maintainers to this repository? I have some tools depending on it, 
https://github.com/johanneswuerbach/saucie https://github.com/johanneswuerbach/ember-cli-sauce, but they need further features which kind of belong into this repository (checksums, retries). I'm definitely willing to contribute the code, but wanted to check whether this project is alive before starting the work.

Ping @bermi, @jlipps, @Jonahss

**Comment by bermi** [comment]
@johanneswuerbach I no longer have time to work on this project so I handed it over to @jlipps and @Jonahss (both Sauce Labs employees). From the issues backlog it looks like we could use some of you help.

Since most requests are for bumping checksums, I've added you to the project. Please consult with @jlipps before accepting significant PR's.
